# Generated by Django 6.0.2 on 2026-02-05 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=20)),
                ('jenis', models.CharField(choices=[('domisili', 'Surat Domisili'), ('usaha', 'Surat Usaha'), ('tidak_mampu', 'Surat Tidak Mampu'), ('kelahiran', 'Surat Kelahiran'), ('kematian', 'Surat Kematian')], max_length=50)),
                ('keterangan', models.TextField(blank=True)),
                ('file_pendukung', models.FileField(blank=True, null=True, upload_to='berkas/')),
                ('file_surat_jadi', models.FileField(blank=True, null=True, upload_to='surat_jadi/')),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='diajukan', max_length=20)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilDesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('geografis', models.TextField()),
                ('demografis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UMKM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('kepala', 'Kepala Desa'), ('sekretaris', 'Sekretaris'), ('kaur', 'Kaur')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
