# Generated by Django 6.0.2 on 2026-02-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkm',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='umkm/'),
        ),
        migrations.AddField(
            model_name='umkm',
            name='kategori',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='umkm',
            name='kontak',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='umkm',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
