# Generated by Django 6.0.2 on 2026-02-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_umkm_foto_umkm_kategori_umkm_kontak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profildesa',
            name='demografis',
        ),
        migrations.RemoveField(
            model_name='profildesa',
            name='geografis',
        ),
        migrations.AddField(
            model_name='profildesa',
            name='galeri_foto',
            field=models.ImageField(blank=True, null=True, upload_to='desa_galeri/'),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='jumlah_penduduk',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='lokasi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profildesa',
            name='potensi_wisata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profildesa',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
